

# This file was *autogenerated* from the file solution.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)# solution.sage
from sage.all import Integer

def rsa_decrypt_small_e3(c):
    
    # Compute the integer cube root and check for exactness
    m, exact = Integer(c).nth_root(_sage_const_3 , truncate_mode=True)

    if not exact:
        print("ERROR: The cube root is not exact. The ciphertext might not follow m^3 < N.")
        exit(_sage_const_1 )

    # Convert to string and decode as UTF-8
    try:
        plaintext = bytes.fromhex(hex(m)[_sage_const_2 :]).decode('utf-8')
        print(f"Decrypted message: {plaintext}")
    except UnicodeDecodeError:
        print("Failed to decode the message as UTF-8.")


if __name__ == "__main__":
    # Input values
    c = Integer(input("Enter ciphertext c: "))
    
    # Decrypt the ciphertext
    rsa_decrypt_small_e3(c)

